wis2box:
    retention: P30D
    topic_hierarchy: country.centre_id.data.core.weather.surface-based-observations.synop
    country: country
    centre_id: centre_id

mcf:
    version: 1.0

metadata:
    identifier: urn:x-wmo:md:country:centre_id:surface-weather-observations
    language: en
    charset: utf8
    hierarchylevel: dataset

identification:
    language: en
    charset: utf8
    title: Surface weather observations from country.centre_id
    abstract: Surface weather observations from country.centre_id
    dates:
        creation: 2021-11-29
        publication: 2021-11-29
    keywords:
        default:
            keywords:
                - surface weather
                - temperature
                - observations
        wmo:
            keywords:
                - weatherObservations
            keywords_type: theme
            vocabulary:
                name: WMO Category Code
                url: https://github.com/wmo-im/wcmp-codelists/blob/main/codelists/WMO_CategoryCode.csv

    extents:
        spatial:
            - bbox: [-180, -90, 190, 90]
              crs: 4326
        temporal:
            - begin: 2021-11-29
              end: null
              resolution: P1H
    url: https://example.org/surface-weather-observations-webpage
    wmo_data_policy: core

contact:
    pointOfContact: &contact_poc
        organization: Your organization name
        url: https://example.org
        individualname: Firstname Lastname
        positionname: Position Name
        phone: NA
        fax: NA
        address: NA
        city: NA
        administrativearea: NA
        postalcode: NA
        country: NA
        email: you@example.org
        hoursofservice: 0700h - 1500h UTC
        contactinstructions: email

    distributor: *contact_poc
