services:
  wis2box-ftp:
    container_name: wis2box-ftp
    image: wmoim/wis2box-ftp:training
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - PASV_ADDRESS=${FTP_HOST}
      - FTP_SSL_ENABLED=${FTP_SSL_ENABLED:-FALSE}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-WARNING}
      - MINIO_ENDPOINT=${WIS2BOX_STORAGE_ENDPOINT:-http://minio:9000}
      - MINIO_ROOT_USER=${WIS2BOX_STORAGE_USER:-minio}
      - MINIO_ROOT_PASSWORD=${WIS2BOX_STORAGE_PASSWORD:-minio123}
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - wis2box-ftp:/home/vsftpd/
volumes:
  wis2box-ftp: