{
 "title": "wis2box workflow monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New/updated files in wis2box-incoming storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "delta(wis2box_storage_incoming_total{}[$__interval])",
     "legendFormat": "New/updated files per hour in wis2box-incoming"
    }
   ]
  },
  {
   "title": "wis2box ERRORs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"wis2box-management\"} |~ `ERROR`"
    }
   ]
  },
  {
   "title": "New/updated files in wis2box-public storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "delta(wis2box_storage_public_total{}[$__interval])",
     "legendFormat": "New/updated files in wis2box-public"
    }
   ]
  },
  {
   "title": "Number of WIS2 notifications published by wis2box",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "delta(wis2box_notify_total[$__interval])",
     "legendFormat": "WIS2 notifications"
    }
   ]
  }
 ]
}