services:
  registry_mirror:
    container_name: registry-mirror
    restart: always
    image: registry:2
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_PROXY_REMOTEURL: "https://index.docker.io"
    ports:
      - "5000:5000"
    volumes:
      - registry-mirror-data:/var/lib/registry

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-12-02T19-19-22Z.fips
    mem_limit: 512m
    memswap_limit: 512m
    restart: always
    command: server --console-address ":9001" /data
    # in a production-setup minio needs to be
    volumes:
      - minio-data:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/minio/health/live"]
      interval: 5s
      timeout: 1s
      retries: 3
    env_file:
      - .env

  mosquitto:
    container_name: mosquitto
    build:
      context: ./mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  minio-data:
  registry-mirror-data:
